"""The priority suite: exact serializer behavior, one case per edge case."""
from nlp_cookies_txt.core import NormalizedCookie, from_netscape, to_netscape

HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# Generated by nlp-cookies-txt. Do not edit.\n"
    "\n"
)


def body(text: str) -> str:
    """Strip the 4-line header + trailing newline to compare data rows only."""
    assert text.startswith(HEADER)
    return text[len(HEADER):].rstrip("\n")


def test_session_cookie_expiry_is_zero():
    c = NormalizedCookie(name="s", value="1", domain="example.com", expires=None)
    assert body(to_netscape([c])).split("\t")[4] == "0"


def test_negative_expiry_is_session():
    c = NormalizedCookie(name="s", value="1", domain="example.com", expires=-1)
    assert body(to_netscape([c])).split("\t")[4] == "0"


def test_fractional_expiry_truncated_to_int():
    c = NormalizedCookie(name="s", value="1", domain="example.com", expires=1893456000.7)
    assert body(to_netscape([c])).split("\t")[4] == "1893456000"


def test_host_only_no_leading_dot_and_false_flag():
    c = NormalizedCookie(name="a", value="b", domain="example.com", host_only=True)
    row = body(to_netscape([c])).split("\t")
    assert row[0] == "example.com"
    assert row[1] == "FALSE"


def test_domain_cookie_gets_leading_dot_and_true_flag():
    c = NormalizedCookie(name="a", value="b", domain="example.com", host_only=False)
    row = body(to_netscape([c])).split("\t")
    assert row[0] == ".example.com"
    assert row[1] == "TRUE"


def test_leading_dot_fallback_when_host_only_unknown():
    c = NormalizedCookie(name="a", value="b", domain=".example.com")  # host_only=None
    row = body(to_netscape([c])).split("\t")
    assert row[1] == "TRUE"


def test_httponly_prefix_on_domain_field():
    c = NormalizedCookie(
        name="sid", value="x", domain="example.com", http_only=True, host_only=True
    )
    assert body(to_netscape([c])).split("\t")[0] == "#HttpOnly_example.com"


def test_secure_flag_uppercased():
    c = NormalizedCookie(name="a", value="b", domain="example.com", secure=True)
    assert body(to_netscape([c])).split("\t")[3] == "TRUE"


def test_host_prefixed_name_passed_through():
    c = NormalizedCookie(name="__Host-sid", value="v", domain="example.com")
    assert body(to_netscape([c])).split("\t")[5] == "__Host-sid"


def test_value_not_url_decoded():
    c = NormalizedCookie(name="a", value="a%20b+c", domain="example.com")
    assert body(to_netscape([c])).split("\t")[6] == "a%20b+c"


def test_trailing_newline_present():
    assert to_netscape([]).endswith("\n")


def test_full_golden_output():
    cookies = [
        NormalizedCookie(
            name="session_id", value="abc123", domain="example.com",
            path="/", secure=True, http_only=True, expires=1893456000, host_only=False,
        ),
        NormalizedCookie(
            name="tempflag", value="1", domain="example.com",
            path="/", secure=False, http_only=False, expires=None, host_only=True,
        ),
    ]
    expected = HEADER + (
        "#HttpOnly_.example.com\tTRUE\t/\tTRUE\t1893456000\tsession_id\tabc123\n"
        "example.com\tFALSE\t/\tFALSE\t0\ttempflag\t1\n"
    )
    assert to_netscape(cookies) == expected


def test_roundtrip_preserves_representable_fields():
    cookies = [
        NormalizedCookie(
            name="sid", value="x", domain="example.com", path="/app",
            secure=True, http_only=True, expires=1893456000, host_only=False,
        ),
    ]
    parsed = from_netscape(to_netscape(cookies))
    assert len(parsed) == 1
    c = parsed[0]
    assert (c.name, c.value, c.secure, c.http_only) == ("sid", "x", True, True)
    assert c.expires == 1893456000
    assert c.domain == ".example.com"


def test_mozillacookiejar_can_load_output(tmp_path):
    from http.cookiejar import MozillaCookieJar

    c = NormalizedCookie(
        name="sid", value="x", domain="example.com", http_only=True,
        expires=1893456000, host_only=False, secure=True,
    )
    p = tmp_path / "cookies.txt"
    p.write_text(to_netscape([c]), encoding="utf-8")
    jar = MozillaCookieJar(str(p))
    jar.load(ignore_discard=True, ignore_expires=True)
    assert any(ck.name == "sid" for ck in jar)
