/**
 * Core: the normalized cookie shape and the canonical Netscape serializer.
 *
 * This MUST stay byte-identical to the Python port (src/cod_cookie_jar/core.py).
 * Both are verified against the shared fixtures in ../../fixtures/golden.
 */

const HEADER = [
  '# Netscape HTTP Cookie File',
  '# https://curl.se/docs/http-cookies.html',
  '# Generated by cod-cookie-jar. Do not edit.',
  '',
];

export const WIRE_VERSION = 1;

/**
 * @typedef {Object} NormalizedCookie
 * @property {string} name
 * @property {string} value
 * @property {string} domain
 * @property {string} [path]
 * @property {boolean} [secure]
 * @property {boolean} [httpOnly]
 * @property {number|null} [expires]      epoch seconds; null/negative => session
 * @property {boolean|null} [hostOnly]    if known, drives includeSubdomains
 * @property {string|null} [sameSite]     carried, not emitted to Netscape
 * @property {string|null} [partitionKey] carried for JSON; flattened in Netscape
 */

function includeSubdomains(c) {
  // Prefer explicit hostOnly when the adapter knows it; else fall back to the
  // leading-dot convention used by real-world cookies.txt files.
  if (c.hostOnly !== undefined && c.hostOnly !== null) return !c.hostOnly;
  return c.domain.startsWith('.');
}

function domainField(c) {
  const inc = includeSubdomains(c);
  let dom = c.domain;
  if (inc && !dom.startsWith('.')) dom = '.' + dom;
  if (!inc && dom.startsWith('.')) dom = dom.replace(/^\.+/, '');
  // #HttpOnly_ prefix is REQUIRED by curl / yt-dlp / MozillaCookieJar for
  // HttpOnly cookies. The reference "Get cookies.txt LOCALLY" extension omits
  // it, which makes strict parsers silently drop the cookie. We do not.
  return c.httpOnly ? '#HttpOnly_' + dom : dom;
}

function expiryField(c) {
  const e = c.expires;
  if (e === undefined || e === null || e < 0) return '0'; // session cookie
  return String(Math.trunc(e)); // integer epoch seconds
}

/** Serialize normalized cookies to a spec-correct Netscape cookies.txt string. */
export function toNetscape(cookies) {
  const rows = cookies.map((c) =>
    [
      domainField(c),
      includeSubdomains(c) ? 'TRUE' : 'FALSE',
      c.path || '/',
      c.secure ? 'TRUE' : 'FALSE',
      expiryField(c),
      c.name,
      c.value, // never URL-decode values
    ].join('\t'),
  );
  return [...HEADER, ...rows].join('\n') + '\n';
}

/** Parse a Netscape cookies.txt back into normalized cookies. */
export function fromNetscape(text) {
  const out = [];
  for (const raw of text.split('\n')) {
    let line = raw;
    let httpOnly = false;
    if (line.startsWith('#HttpOnly_')) {
      httpOnly = true;
      line = line.slice('#HttpOnly_'.length);
    } else if (!line.trim() || line.startsWith('#')) {
      continue;
    }
    const parts = line.split('\t');
    if (parts.length !== 7) continue;
    const [domain, includeSub, path, secure, expiry, name, value] = parts;
    out.push({
      name,
      value,
      domain,
      path,
      secure: secure.toUpperCase() === 'TRUE',
      httpOnly,
      expires: expiry === '0' ? null : Number(expiry),
      hostOnly: includeSub.toUpperCase() !== 'TRUE',
    });
  }
  return out;
}

/** True if the cookie is partitioned (CHIPS) and so loses scope in Netscape. */
export function isPartitioned(c) {
  return c.partitionKey !== undefined && c.partitionKey !== null;
}

/** Normalize an arbitrary wire dict (camelCase or snake_case) to our shape. */
export function fromWire(d) {
  const pick = (camel, snake) => (camel in d ? d[camel] : d[snake]);
  const expires = pick('expires', 'expires');
  return {
    name: d.name,
    value: d.value,
    domain: d.domain,
    path: d.path || '/',
    secure: Boolean(pick('secure', 'secure')),
    httpOnly: Boolean(pick('httpOnly', 'http_only')),
    expires: expires === undefined || expires === null ? null : Number(expires),
    hostOnly: pick('hostOnly', 'host_only') ?? null,
    sameSite: pick('sameSite', 'same_site') ?? null,
    partitionKey: pick('partitionKey', 'partition_key') ?? null,
  };
}

function toWire(c) {
  const d = {
    name: c.name,
    value: c.value,
    domain: c.domain,
    path: c.path || '/',
    secure: Boolean(c.secure),
    httpOnly: Boolean(c.httpOnly),
  };
  if (c.expires !== undefined && c.expires !== null) d.expires = c.expires;
  if (c.hostOnly !== undefined && c.hostOnly !== null) d.hostOnly = c.hostOnly;
  if (c.sameSite !== undefined && c.sameSite !== null) d.sameSite = c.sameSite;
  if (c.partitionKey !== undefined && c.partitionKey !== null) {
    d.partitionKey = c.partitionKey;
  }
  return d;
}

/** Serialize to the CHIPS-preserving JSON wire format. */
export function toJson(cookies, indent = 2) {
  return (
    JSON.stringify(
      {
        format: 'cod-cookie-jar',
        version: WIRE_VERSION,
        cookies: cookies.map(toWire),
      },
      null,
      indent,
    ) + '\n'
  );
}

/** Parse the JSON wire format (also accepts a bare array of cookie dicts). */
export function fromJson(text) {
  const data = JSON.parse(text);
  const items = Array.isArray(data) ? data : data.cookies;
  return items.map(fromWire);
}

/** Keep cookies whose domain matches `domain` or a parent/child of it. */
export function filterDomain(cookies, domain) {
  if (!domain) return cookies;
  const needle = domain.replace(/^\.+/, '').toLowerCase();
  return cookies.filter((c) => {
    const d = c.domain.replace(/^\.+/, '').toLowerCase();
    return needle === d || needle.endsWith('.' + d) || d.endsWith('.' + needle);
  });
}
