"""Core: the normalized cookie shape and the canonical Netscape serializer.

All format logic lives here so every adapter produces byte-identical output.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Optional

_HEADER = [
    "# Netscape HTTP Cookie File",
    "# https://curl.se/docs/http-cookies.html",
    "# Generated by cod-cookie-jar. Do not edit.",
    "",
]


@dataclass
class NormalizedCookie:
    """Adapter-agnostic cookie.

    ``expires``: epoch seconds. ``None`` or a negative value == session cookie.
    ``host_only``: if known, drives the includeSubdomains flag; otherwise the
    serializer falls back to the leading-dot convention.
    """

    name: str
    value: str
    domain: str
    path: str = "/"
    secure: bool = False
    http_only: bool = False
    expires: Optional[float] = None
    host_only: Optional[bool] = None
    same_site: Optional[str] = None      # carried, not emitted to Netscape
    partition_key: Optional[str] = None  # carried for JSON export; flattened in txt


def _include_subdomains(c: NormalizedCookie) -> bool:
    # Prefer explicit host_only when the adapter knows it; else fall back to the
    # leading-dot convention used by real-world cookies.txt files.
    if c.host_only is not None:
        return not c.host_only
    return c.domain.startswith(".")


def _domain_field(c: NormalizedCookie) -> str:
    inc = _include_subdomains(c)
    dom = c.domain
    if inc and not dom.startswith("."):
        dom = "." + dom
    if not inc and dom.startswith("."):
        dom = dom.lstrip(".")
    # #HttpOnly_ prefix is REQUIRED by curl / yt-dlp / MozillaCookieJar for
    # HttpOnly cookies. The reference "Get cookies.txt LOCALLY" extension omits
    # it, which makes strict parsers silently drop the cookie. We do not.
    return ("#HttpOnly_" + dom) if c.http_only else dom


def _expiry_field(c: NormalizedCookie) -> str:
    if c.expires is None or c.expires < 0:
        return "0"                      # session cookie
    return str(int(c.expires))          # integer epoch seconds; truncate fractional


def to_netscape(cookies: Iterable[NormalizedCookie]) -> str:
    """Serialize normalized cookies to a spec-correct Netscape cookies.txt string."""
    rows = []
    for c in cookies:
        rows.append(
            "\t".join(
                [
                    _domain_field(c),
                    "TRUE" if _include_subdomains(c) else "FALSE",
                    c.path or "/",
                    "TRUE" if c.secure else "FALSE",
                    _expiry_field(c),
                    c.name,
                    c.value,  # never URL-decode values
                ]
            )
        )
    return "\n".join(_HEADER + rows) + "\n"


def is_partitioned(c: NormalizedCookie) -> bool:
    """True if the cookie is partitioned (CHIPS) and so loses scope in Netscape."""
    return c.partition_key is not None


# --- JSON wire format -------------------------------------------------------
# Canonical schema is camelCase (matching CDP / Playwright / the shared golden
# fixtures) so the Python and Node ports can exchange cookie sets losslessly.
# Unlike Netscape, this format preserves sameSite and partitionKey (CHIPS).

WIRE_VERSION = 1

_WIRE_KEYS = {
    "name": "name",
    "value": "value",
    "domain": "domain",
    "path": "path",
    "secure": "secure",
    "httpOnly": "http_only",
    "expires": "expires",
    "hostOnly": "host_only",
    "sameSite": "same_site",
    "partitionKey": "partition_key",
}


def to_wire(c: NormalizedCookie) -> dict:
    """NormalizedCookie -> camelCase dict, omitting unset optional fields."""
    d = {
        "name": c.name,
        "value": c.value,
        "domain": c.domain,
        "path": c.path,
        "secure": c.secure,
        "httpOnly": c.http_only,
    }
    if c.expires is not None:
        d["expires"] = c.expires
    if c.host_only is not None:
        d["hostOnly"] = c.host_only
    if c.same_site is not None:
        d["sameSite"] = c.same_site
    if c.partition_key is not None:
        d["partitionKey"] = c.partition_key
    return d


def from_wire(d: dict) -> NormalizedCookie:
    """camelCase (or snake_case) dict -> NormalizedCookie."""
    def get(camel: str, default=None):
        if camel in d:
            return d[camel]
        return d.get(_WIRE_KEYS[camel], default)

    expires = get("expires")
    return NormalizedCookie(
        name=get("name"),
        value=get("value"),
        domain=get("domain"),
        path=get("path") or "/",
        secure=bool(get("secure", False)),
        http_only=bool(get("httpOnly", False)),
        expires=None if expires is None else float(expires),
        host_only=get("hostOnly"),
        same_site=get("sameSite"),
        partition_key=get("partitionKey"),
    )


def to_json(cookies: Iterable[NormalizedCookie], indent: int = 2) -> str:
    """Serialize to the CHIPS-preserving JSON wire format."""
    import json

    payload = {
        "format": "cod-cookie-jar",
        "version": WIRE_VERSION,
        "cookies": [to_wire(c) for c in cookies],
    }
    return json.dumps(payload, indent=indent) + "\n"


def from_json(text: str) -> list[NormalizedCookie]:
    """Parse the JSON wire format (also accepts a bare list of cookie dicts)."""
    import json

    data = json.loads(text)
    items = data["cookies"] if isinstance(data, dict) else data
    return [from_wire(d) for d in items]


def from_netscape(text: str) -> list[NormalizedCookie]:
    """Parse a Netscape cookies.txt back into NormalizedCookie objects.

    Round-trips the fields representable in the format (drops same_site /
    partition_key, which the format cannot express).
    """
    out: list[NormalizedCookie] = []
    for raw in text.splitlines():
        line = raw.rstrip("\n")
        http_only = False
        if line.startswith("#HttpOnly_"):
            http_only = True
            line = line[len("#HttpOnly_") :]
        elif not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 7:
            continue
        domain, include_sub, path, secure, expiry, name, value = parts
        exp = None if expiry == "0" else float(expiry)
        out.append(
            NormalizedCookie(
                name=name,
                value=value,
                domain=domain,
                path=path,
                secure=(secure.upper() == "TRUE"),
                http_only=http_only,
                expires=exp,
                host_only=(include_sub.upper() != "TRUE"),
            )
        )
    return out
