"""Writes the language-neutral golden fixtures consumed by BOTH the Python and
Node test suites.

The `expectedNetscape` strings here are hand-authored (not generated from either
implementation), so they act as an independent oracle: if the Python and Node
serializers ever diverge, one of them fails against these files.

Run:  python tools/make_fixtures.py
"""
import json
import pathlib

H = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# Generated by nlp-cookies-txt. Do not edit.\n"
    "\n"
)

CASES = [
    {
        "name": "empty",
        "description": "No cookies: header only, still ends with a newline.",
        "cookies": [],
        "expectedNetscape": H,
    },
    {
        "name": "session_cookie_expiry_zero",
        "description": "expires omitted => session cookie => expiry field is 0.",
        "cookies": [
            {"name": "s", "value": "1", "domain": "example.com", "path": "/",
             "hostOnly": True}
        ],
        "expectedNetscape": H + "example.com\tFALSE\t/\tFALSE\t0\ts\t1\n",
    },
    {
        "name": "negative_expiry_is_session",
        "description": "expires=-1 (Playwright/Puppeteer session marker) => 0.",
        "cookies": [
            {"name": "s", "value": "1", "domain": "example.com", "path": "/",
             "expires": -1, "hostOnly": True}
        ],
        "expectedNetscape": H + "example.com\tFALSE\t/\tFALSE\t0\ts\t1\n",
    },
    {
        "name": "fractional_expiry_truncated",
        "description": "CDP returns a double; expiry must be an integer epoch second.",
        "cookies": [
            {"name": "s", "value": "1", "domain": "example.com", "path": "/",
             "expires": 1893456000.7, "hostOnly": True}
        ],
        "expectedNetscape": H + "example.com\tFALSE\t/\tFALSE\t1893456000\ts\t1\n",
    },
    {
        "name": "host_only_cookie",
        "description": "hostOnly => no leading dot, includeSubdomains FALSE.",
        "cookies": [
            {"name": "a", "value": "b", "domain": "example.com", "path": "/",
             "hostOnly": True}
        ],
        "expectedNetscape": H + "example.com\tFALSE\t/\tFALSE\t0\ta\tb\n",
    },
    {
        "name": "domain_cookie_leading_dot",
        "description": "hostOnly=false => leading dot added, includeSubdomains TRUE.",
        "cookies": [
            {"name": "a", "value": "b", "domain": "example.com", "path": "/",
             "hostOnly": False}
        ],
        "expectedNetscape": H + ".example.com\tTRUE\t/\tFALSE\t0\ta\tb\n",
    },
    {
        "name": "leading_dot_fallback",
        "description": "hostOnly unknown => fall back to the leading-dot convention.",
        "cookies": [
            {"name": "a", "value": "b", "domain": ".example.com", "path": "/"}
        ],
        "expectedNetscape": H + ".example.com\tTRUE\t/\tFALSE\t0\ta\tb\n",
    },
    {
        "name": "httponly_prefix",
        "description": "HttpOnly MUST get the #HttpOnly_ prefix on the domain field.",
        "cookies": [
            {"name": "sid", "value": "x", "domain": "example.com", "path": "/",
             "httpOnly": True, "hostOnly": True}
        ],
        "expectedNetscape": H + "#HttpOnly_example.com\tFALSE\t/\tFALSE\t0\tsid\tx\n",
    },
    {
        "name": "httponly_domain_cookie",
        "description": "#HttpOnly_ prefix combines with the leading dot.",
        "cookies": [
            {"name": "sid", "value": "x", "domain": "example.com", "path": "/",
             "httpOnly": True, "hostOnly": False}
        ],
        "expectedNetscape": H + "#HttpOnly_.example.com\tTRUE\t/\tFALSE\t0\tsid\tx\n",
    },
    {
        "name": "secure_flag",
        "description": "secure serializes as an uppercase TRUE.",
        "cookies": [
            {"name": "a", "value": "b", "domain": "example.com", "path": "/",
             "secure": True, "hostOnly": True}
        ],
        "expectedNetscape": H + "example.com\tFALSE\t/\tTRUE\t0\ta\tb\n",
    },
    {
        "name": "host_prefixed_name",
        "description": "__Host- / __Secure- names pass through verbatim.",
        "cookies": [
            {"name": "__Host-sid", "value": "v", "domain": "example.com",
             "path": "/", "secure": True, "hostOnly": True}
        ],
        "expectedNetscape": H + "example.com\tFALSE\t/\tTRUE\t0\t__Host-sid\tv\n",
    },
    {
        "name": "value_not_url_decoded",
        "description": "Values are emitted raw; never URL-decode.",
        "cookies": [
            {"name": "a", "value": "a%20b+c", "domain": "example.com", "path": "/",
             "hostOnly": True}
        ],
        "expectedNetscape": H + "example.com\tFALSE\t/\tFALSE\t0\ta\ta%20b+c\n",
    },
    {
        "name": "nested_path_preserved",
        "description": "Non-root paths are preserved verbatim.",
        "cookies": [
            {"name": "a", "value": "b", "domain": "example.com", "path": "/app/sub",
             "hostOnly": True}
        ],
        "expectedNetscape": H + "example.com\tFALSE\t/app/sub\tFALSE\t0\ta\tb\n",
    },
    {
        "name": "chips_partitioned_flattened",
        "description": (
            "CHIPS: partitionKey is preserved in JSON but cannot be expressed in "
            "Netscape, so the cookie is emitted flattened (partition scope lost)."
        ),
        "cookies": [
            {"name": "pc", "value": "v", "domain": "cdn.example.com", "path": "/",
             "secure": True, "hostOnly": True,
             "partitionKey": "https://top.example"}
        ],
        "expectedNetscape": H + "cdn.example.com\tFALSE\t/\tTRUE\t0\tpc\tv\n",
    },
    {
        "name": "full_mixed",
        "description": "Multi-row golden: HttpOnly+secure+persistent, then session.",
        "cookies": [
            {"name": "session_id", "value": "abc123", "domain": "example.com",
             "path": "/", "secure": True, "httpOnly": True,
             "expires": 1893456000, "hostOnly": False},
            {"name": "tempflag", "value": "1", "domain": "example.com",
             "path": "/", "hostOnly": True},
        ],
        "expectedNetscape": H
        + "#HttpOnly_.example.com\tTRUE\t/\tTRUE\t1893456000\tsession_id\tabc123\n"
        + "example.com\tFALSE\t/\tFALSE\t0\ttempflag\t1\n",
    },
]

def main():
    out = pathlib.Path(__file__).resolve().parents[1] / "fixtures" / "golden"
    out.mkdir(parents=True, exist_ok=True)
    for case in CASES:
        path = out / f"{case['name']}.json"
        path.write_text(json.dumps(case, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(CASES)} fixtures -> {out}")


if __name__ == "__main__":
    main()
